version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      #ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    ports:
      - 5601:5601
    networks:
     - elastic
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    volumes:
     - ./data/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
     - ./data/filebeat/logs:/usr/share/filebeat/logs
    networks:
     - elastic
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.16.2
    volumes:
     - ./data/logstash/pipeline:/usr/share/logstash/pipeline/
    networks:
     - elastic

networks:
  elastic:
    driver: bridge
